import { toIdentifier } from './lang.js'
import type { AppSpec, Entity } from '../../types.js'

/**
 * A browser-backed store for applications that document data but no API.
 *
 * Plenty of specifications describe a real application — a data model, screens
 * that create and list and edit — and name no endpoints at all, because none
 * exist yet. Those used to generate as static sample data behind a notice:
 * every screen correct, every button inert, nothing you could actually use.
 *
 * This emits a store instead, so the same screens work. Created records
 * persist, lists update, a refresh keeps them. Nothing about the API path
 * changes — where endpoints ARE documented they are still the only way data
 * moves, and this file is not emitted at all.
 */

/**
 * Entities worth persisting.
 *
 * This used to require a documented `id`, on the theory that identity marks a
 * record. People do not write specifications that way — a tree of "Project /
 * Owner / Status / Updates" describes an application perfectly and mentions no
 * id, because an id is an implementation detail. Requiring one meant nothing
 * was storable, no store was emitted, and an app that was meant to work fell
 * back to sample data that could not.
 *
 * So any named shape with more than one field gets a collection. The store
 * assigns ids itself, and a collection nothing ever reads costs one unused
 * hook — much cheaper than the application not working.
 */
export function storableEntities(appSpec: AppSpec): Entity[] {
  return appSpec.entities.filter((entity) => entity.fields.length > 1)
}

/** `ProjectUpdate` -> `projectUpdates`, the name its collection is stored under. */
export function collectionName(entityName: string): string {
  const base = toIdentifier(entityName, 'record')
  const camel = base[0] ? base[0].toLowerCase() + base.slice(1) : 'record'
  if (/(s|x|z|ch|sh)$/i.test(camel)) return `${camel}es`
  if (/[^aeiou]y$/i.test(camel)) return `${camel.slice(0, -1)}ies`
  return `${camel}s`
}

export function emitLocalStore(appSpec: AppSpec, projectId: string): string {
  const entities = storableEntities(appSpec)

  const collections = entities
    .map((entity) => `  ${collectionName(entity.name)}: '${entity.name}',`)
    .join('\n')

  const typeImports = entities.map((e) => e.name).join(', ')

  const hooks = entities
    .map((entity) => {
      const name = collectionName(entity.name)
      const hook = `use${name[0]!.toUpperCase()}${name.slice(1)}`
      return `/** Every ${entity.name}, and the ways to change them. */
export function ${hook}() {
  return useCollection<${entity.name}>('${name}')
}`
    })
    .join('\n\n')

  return `/**
 * Local data store.
 *
 * Your documents describe this application's data but no API to hold it, so it
 * lives in this browser under the key below. Records survive a refresh and are
 * private to this device — clearing site data clears them.
 *
 * Generated by Spec2UI from the documented data model. When you have an API,
 * re-generate with its endpoints and screens will use those instead.
 */
import { useCallback, useEffect, useState } from 'react'
import type { ${typeImports} } from './types'

const STORAGE_KEY = 'spec2ui:${projectId}'

/** The documented shapes this store keeps. */
export const collections = {
${collections}
} as const

export type CollectionName = keyof typeof collections

/** Anything stored gets an id, whether or not the caller supplied one. */
export type Stored<T> = T & { id: string }

type Database = Record<string, Stored<Record<string, unknown>>[]>

/*
 * Memory is the store; localStorage is how it survives a refresh.
 *
 * Reading straight from localStorage on every call looks simpler and fails in
 * one specific place that matters: a sandboxed preview iframe, a private
 * window, or blocked site data makes every access throw. Treated as "empty",
 * each write then appeared to succeed and vanished — adding a record did
 * nothing at all, silently.
 *
 * So the truth lives in memory, which always works, and persistence is a
 * best-effort copy on top. Where storage is unavailable the application behaves
 * correctly for the session and says so, instead of quietly losing everything.
 */
let memory: Database | null = null

export const persistence: { available: boolean; reason: string } = {
  available: true,
  reason: '',
}

function readAll(): Database {
  if (memory) return memory

  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    memory = raw ? (JSON.parse(raw) as Database) : {}
  } catch (err) {
    persistence.available = false
    persistence.reason = err instanceof Error ? err.message : 'storage is unavailable'
    memory = {}
  }

  return memory
}

function writeAll(db: Database): void {
  // Kept whatever happens next — this is the copy the application reads.
  memory = db

  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(db))
  } catch (err) {
    persistence.available = false
    persistence.reason = err instanceof Error ? err.message : 'storage is unavailable'
  }
}

/*
 * One notifier for the whole store.
 *
 * Two screens reading the same collection must see the same rows: a list that
 * still shows yesterday's records after a form created one is the bug this
 * avoids. Every write tells every hook to re-read.
 */
const listeners = new Set<() => void>()
const notify = () => listeners.forEach((fn) => fn())

// A write in another tab is a write; the browser tells us about those too.
if (typeof window !== 'undefined') {
  window.addEventListener('storage', (event) => {
    if (event.key === STORAGE_KEY) notify()
  })
}

function newId(): string {
  return \`\${Date.now().toString(36)}\${Math.random().toString(36).slice(2, 8)}\`
}

export interface Collection<T> {
  items: Stored<T>[]
  create: (values: Partial<T>) => Stored<T>
  update: (id: string, values: Partial<T>) => void
  remove: (id: string) => void
  /** One record by id, or undefined — what a detail screen needs. */
  byId: (id: string | undefined) => Stored<T> | undefined
}

export function useCollection<T>(name: string): Collection<T> {
  const [items, setItems] = useState<Stored<T>[]>(() => (readAll()[name] ?? []) as Stored<T>[])

  const refresh = useCallback(() => {
    setItems((readAll()[name] ?? []) as Stored<T>[])
  }, [name])

  useEffect(() => {
    listeners.add(refresh)
    refresh()
    return () => {
      listeners.delete(refresh)
    }
  }, [refresh])

  const create = useCallback(
    (values: Partial<T>) => {
      const db = readAll()
      const record = { ...(values as Record<string, unknown>), id: newId() } as Stored<T>
      db[name] = [...(db[name] ?? []), record as never]
      writeAll(db)
      notify()
      return record
    },
    [name],
  )

  const update = useCallback(
    (id: string, values: Partial<T>) => {
      const db = readAll()
      db[name] = (db[name] ?? []).map((row) => (row.id === id ? { ...row, ...values } : row))
      writeAll(db)
      notify()
    },
    [name],
  )

  const remove = useCallback(
    (id: string) => {
      const db = readAll()
      db[name] = (db[name] ?? []).filter((row) => row.id !== id)
      writeAll(db)
      notify()
    },
    [name],
  )

  const byId = useCallback(
    (id: string | undefined) => (id ? items.find((row) => row.id === id) : undefined),
    [items],
  )

  return { items, create, update, remove, byId }
}

${hooks}
`
}
